# Generated by Django 4.2.25 on 2025-11-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost to participate in the activity (0 for free)', max_digits=8),
        ),
    ]
