# Generated by Django 4.2.23 on 2025-11-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_subject_levels_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='Course.extracurricularactivity'),
        ),
    ]
