# Generated by Django 4.2.26 on 2025-11-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_liveclass_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='Course.academiclevel'),
        ),
    ]
